### ISSUE TITLE
how to use in windows?

### ISSUE THREAD

**Issue by Miracles666** [gand3lf/semgrepper#7]
I have already set up and exported the environment variable for semgrep in Windows WSL. ：
![image](https://user-images.githubusercontent.com/40236845/233580324-8beab9de-0423-40d5-80d4-3d4119e4e128.png)
It still prompts.
![image](https://user-images.githubusercontent.com/40236845/233580583-901159d9-ff9a-4598-948b-76845130dc77.png)
nothing output:
![image](https://user-images.githubusercontent.com/40236845/233580680-35b5bb36-a704-4aec-ad94-0dffc724ce85.png)

**Comment by Miracles666** [comment]
I seem to have found a solution by adding an additional wsl in front of it
![image](https://user-images.githubusercontent.com/40236845/233583159-f6a3ce61-26f3-4be4-bfdb-25b34c447330.png)

**Comment by gand3lf** [comment]
Hi @Miracles666, thanks for your analysis. In case you need, I have provided 2 debug versions of the project linked here: https://github.com/gand3lf/semgrepper/issues/1#issuecomment-1463554712

Please, could you provide me the output of the 2 debug versions?

**Comment by Miracles666** [comment]
environment variables:
java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because the return value of "java.util.Map.get(Object)" is null
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:32)
	at burp.ex.w(Unknown Source)
	at burp.lbn.h(Unknown Source)
	at burp.lbc.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)


Message:
java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because the return value of "java.util.Map.get(Object)" is null
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:32)
	at burp.ex.w(Unknown Source)
	at burp.lbn.h(Unknown Source)
	at burp.lbc.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)


both same ,crarzy!  my burp version is  2023.2

**Comment by gand3lf** [comment]
@Miracles666 the issues seems to be related to the envs... Could you try this version? 
[Semgrepper.zip](https://github.com/gand3lf/semgrepper/files/11294721/Semgrepper.zip)

**Comment by Miracles666** [comment]
hi @gand3lf , it try this version ,but it nothing error output 
![image](https://user-images.githubusercontent.com/40236845/233610485-48de75af-2111-43ea-8461-b6e8bd1249f6.png)
but it still output:
![image](https://user-images.githubusercontent.com/40236845/233610610-a62f4db0-2936-4211-93f4-b5d93e20d0da.png)

**Comment by gand3lf** [comment]
@Miracles666 thank you for your test. Could you try also this version?
[Semgrepper.zip](https://github.com/gand3lf/semgrepper/files/11295900/Semgrepper.zip)

This one should work for Win, Lin and Mac.

**Comment by Miracles666** [comment]
good job!  it's work! thank you!

**Comment by gand3lf** [comment]
Good! You can use that version for now. As soon as possible I will push the changes also in the BurpSuite official repository
